import './Education.css';


function Education() {
  return (
    <div id = "education">
      <p>I was educated at the University of Texas at Austin (UT Austin) from 2006 – 2017 and then again in 2021. I have a bachelor of arts in Anthropology, a master of arts in Asian Cultures and Languages, and a coding boot camp certificate from the university. I also have a Project Management Certificate from Google. In this section of the portfolio, I describe my education and how it remains relevant to me today.</p>
      <p>I entered UT Austin in 2006, without knowing what I wanted to study. The first semester there, on the beautiful campus, I took a course with Professor Ward Keeler, with whom as an advisor, it turned out, I would study the discipline of anthropology for the next decade. The course was called “Expressive Cultures,” and I remember Professor Keeler discussed fascinating topics about American culture such as associations people have with language (as seen in the documentary, “American Tongues”), nationalism, and other aspects of culture. Eloquent and precise with his lectures, Professor Keeler, in addition to his message, impressed me. This was someone I could learn from, I thought. Although I had a connection with Professor Keeler, who became my informal mentor, academic advisor, and running buddy, I didn’t take another course with him until my last year of undergraduate education in 2011. The course was “Anthropology and the Self,” but I can’t remember the reading list today. The self is an interesting concept, especially as one imagines one’s place in a hierarchy, and hierarchy is Professor Keeler’s main interest.</p>
      <p>What did I do for the rest of my undergraduate degree? At the urgence of Professor Keeler, I chose a country where I wanted to study anthropology: India. So, I started taking courses about India: “Nationalism and Gender in South Asia” with the influential Professor Kamala Visveswaran, “Goddesses in World Religions and Cultures” and “Gender / Sex / Family in Indian Religions / Cultures” with the similarly statured Professor Martha Selby, and “Globalization and Indian Society” with the interesting Professor Kaushik Ghosh. </p>
      <p>I learned about the country, and I started to learn an Indian language: Hindi. I chose Hindi because UT Austin has the Hindi-Urdu Flagship, the preeminent Hindi teaching department in the USA. The then-director of the flagship, Professor Rupert Snell, taught many of the courses, and I was privileged to take “First Year Hindi II” and “Panorama of Hindi Literature” from him while I was an undergraduate. Later, Professor Snell also became an informal academic advisor to me, writing letters of recommendation and co-supervising my master’s report.</p>
      <p>I did other things as an undergraduate. I took elective courses, some required courses like science and math, and also courses for my minor: history. For example, in 2008, I was admitted to the Normandy Scholars history program, a selective program for a group of students together to take five courses about World War II from professors who then tour the students around European sites that summer. It was an enlightening program, and I received incredible practice in reading and writing at an advanced level for undergraduates.</p>
      <p>In the fall of 2012, I entered graduate school at UT Austin. Instead of the Department of Anthropology, however, I entered the Department of Asian Studies, where I would be able to enhance my language abilities – language ability is a key requirement for anthropological fieldwork. That semester I took a course “Cultural Constructions of Masculinity” by Professor Keeler; the course focused on the different understandings of masculinity. I also took a course from Professor Snell, “Conference Course in Hindi Language and Culture,” and Professor Snell had me and another student read various excerpts such as from the BBC Hindi and also older texts such as by the father of Modern Hindi: Bharatendu Harishchandra.</p>
      <p>The following semester, I took another course with Professor Keeler, “Anthropology of Buddhism,” and we read books (every seminar, Professor Keeler assigned at least 10-11 books, 1 per week) about the religion. One of the assigned texts was Steven Collins’s <i>Nirvana and Other Buddhist Felicities</i>, which rivals Sheldon Pollock’s <i>The Language of the Gods in the World of Men</i> as a magisterial treatise about the role of language and religion in South Asian history.</p>
      <p>I took other courses from other professors too, and I learned about translation, history, and diaspora. By 2014, I was ready to write a master’s report, and I chose the topic of the history of Hindi. In the report, I trace the history of Hindi through its beginning in regional languages like Braj Bhasha into its codification by the British colonialists at the Fort William College in Kolkata in the early 19th century – and into the language support by various organizations and movements, eventually becoming the <i>raajabhaashaa</i> or “official language” of the Indian Constitution. </p>
      <p>With so much focus on my language abilities, I felt ready to enter the next phase of my graduate school career: the PhD. Supported by a Graduate Research Fellowship from the National Science Foundation, I returned to the Department of Anthropology. The PhD was a joint MA/PhD program, so for three years, I took courses to satisfy requirements before I took qualification exams to enter the PhD phase of the degree. I stopped taking Hindi courses after the master’s degree and focused solely on anthropology.</p>
      <p>The first semester in the anthropology MA/PhD program, I took a course from Professor Keeler called “Weber, Dumont, and Bourdieu.” This was probably one of my favorite courses that I ever took. Max Weber was a founder of sociology, and Bourdieu was the leading sociologist of the 20th century. Dumont was an anthropologist influenced by structuralism, and wasn’t directly related to Weber and Bourdieu, though, given Professor Keeler’s interest in hierarchy, that’s the perspective from which we analyzed all three thinkers during our discussions in the seminar. </p>
      <p>The following semester, in the spring of 2015, I took another course from Professor Keeler: “Authenticity: From Herder to Oprah,” in which we studied the concept of authenticity. I remember one of the assigned texts was <i>Culture and Authenticity</i> by the anthropologist Charles Lindholm, and in the book, Lindholm posits that authenticity is either a derivation from a source or a current resemblance to it. From that insight, we analyzed people’s claims of cultural authenticity especially as they related to hierarchy.</p>
      <p>I took two more courses from Professor Keeler before my qualification exams: “Masculinities” in 2016 and “Globalization” in 2017. Fascinating topics, I already had some exposure to the concept of masculinity from an earlier course about the subject. This time, however, the discussion surrounded the ideas of R.W. Connell, a central theorist we studied. Globalization was also an interesting course. We continued to read a wide variety of books, and one of the more notable ones was <i>Modernity At Large: Cultural Dimensions of Globalization</i> by Arjun Appadurai. Appadurai examines ethnicity, technology, finance, media, and ideas as they circle the globe and take on local characteristics in instantiations such as Bollywood movies.</p>
      <p>In 2017, I took and failed my qualification exams for the PhD. There were some personal reasons for the failure that I don’t want to go into here. Nonetheless, I was devastated by the situation. I had always assumed that I would become an anthropology professor at a university. Now, this was no longer a possibility. My future had been upended. </p>
      <p>I returned to the small house where I lived and thought for a few weeks about what my next steps might be. I had seen multiple advertisements for coding boot camps that claimed a person could gain a certificate in three months that would allow them to find a good job as a web developer or coder. My younger brother is a senior software engineer, and he encouraged me to pursue the idea, first by studying by myself and then later by joining a boot camp.</p>
      <p>For the next three years, I learned web development languages: JavaScript, Python, HTML, and CSS. I learned web development frameworks like React and Django. I built a portfolio on GitHub. I also began to study data structures and algorithms. After three years of study, I felt ready to enter the UT Austin coding boot camp, which I did in 2021. I learned from a great teacher and did many projects. The boot camp was tough – the most difficult course I’ve ever taken – but my preparation served me well, and I completed the boot camp and obtained the certificate.</p>
      <p>After I obtained the coding boot camp certificate, I tried for a year to find a job as a web developer. But I could not land even a single interview. For whatever reason, the certificate did not open doors for me. My experienced brother says that competition among people with certificates and degrees results in the need to have highly sophisticated portfolio projects, and although my portfolio projects were great, they were not great enough to win me an interview.</p>
      <p>By 2023, I began thinking about other opportunities for work. I gained another credential that spring, the Google Project Management Certificate. The online course was rigorous, with dozens of quizzes, assessments, and projects to evaluate the student as they progressed through the material. The content of the course was fun for me, and I enjoyed learning about it. Also, the certificate immediately was useful, as I found an internship through it as an Estimator for a construction company, which later turned into an opportunity for being a Project Coordinator for an architectural design firm. </p>
      <p>That’s the history of my education. Anthropology, Hindi, coding, and project management are the subjects in which I’m educated, and they remain relevant to me today. I continue to consider hierarchy in sociocultural contexts, the main lesson I learned from Professor Keeler while studying anthropology. I am a Hindi teacher on the Preply app and engage in lively conversation on the Hello Talk app. I continue to code data structures and algorithms and also web apps for fun logic puzzles. Finally, I’m searching for a job in project management, so I hope the certificate will continue to be useful. I have had a great education. I’ve read hundreds of books and articles, studied a language, learned how to code, and gained a business certificate to help find a job. It’s been a wild ride, and I’m enjoying continuing to learn as an adult.</p>
    </div> 
  );
}

export default Education;
