import './Education.css';


function Education() { 
  return ( 
    <div> 
      <h1>Education</h1>
      <p id = "firstParagraph">I was educated at The University of Texas at Austin (UT), a university consistently ranked among the top 50 universities in the world. From the university, I received a BA in anthropology, an MA in Asian cultures and languages, and a coding boot camp certificate. I also have a certificate from a project management course by Google. In this section of my portfolio, I will describe my education and the ways it remains relevant to me today.</p>
      <p>I entered the beautiful campus at UT in the fall of 2006. Before then, the son of a geophysicist, I had attended Blue Ribbon schools, and I had read widely in literature, both fiction and nonfiction. When I entered college, I already had 12 hours of college credit from Advanced Placement classes, which I had taken in high school.</p>
      <p>Despite my great education up to that point, I was also impressed by UT. The quality of education was high. I took a range of classes as an undergraduate, mostly in anthropology, but I also took subjects like history and Hindi. I chose to study Hindi in part because of the exceptional faculty for the language, who were present at the university in a department called the Hindi-Urdu Flagship (HUF). HUF is a Department of Defense national flagship program that recruits great faculty, making it the leading Hindi department in the nation. I was not in the flagship program, but I took Hindi classes from the director of the flagship.</p>
      <p>As an undergraduate, I also participated in the Normandy Scholar Program (NSP). In the selective history program, approximately 20 students take the same 5 courses together, with each course focusing on a different aspect of World War II. Focused also on the development of essay writing, the NSP concluded with a trip to Europe where the professors toured historical sites with us students. The material of the program was difficult, both in terms of literary history and also the sad content. But I improved greatly as a student of history, a reader, and a writer.</p>
      <p>With these forays into Hindi and history, my main focus was on anthropology, and I took courses in what is now called sociocultural anthropology, many of which focused on India. In 2009, I even traveled to India, where I lived for a year or so, studying Hindi in Jaipur at The American Institute of Indian Studies (AIIS). That was my first year in India, and I’ve spent approximately 4 years there total since my first visit. I enjoyed my time in India, and my Hindi improved significantly from the immersive experience. The quality of instruction is high at AIIS, and I made good friends there. I also began informal anthropological fieldwork in Jaipur, developing interlocutors and learning Indian ideas about society and culture.</p>
      <p>In 2011, I received my BA in anthropology. After graduation, I decided to apply to graduate school. At the time, I wanted to obtain a PhD in sociocultural anthropology and to become a professor in the social science. An advisor suggested that I first take an MA in Asian cultures and languages, which would enhance my Hindi skills as preparation for conducting ethnographic fieldwork for a PhD dissertation later in anthropology. I was accepted to The Department of Asian Studies at UT for an MA program in Asian cultures and languages. My plan was to focus on Hindi.</p>
      <p>Funded by Foreign Language Area Scholarships (FLAS) during the 2 years in The Department of Asian Studies, I took 4 Hindi courses, which mostly covered literature, both poetry and prose. My Hindi ability grew considerably, and I also took courses in anthropology, including a course about anthropological theory. For the MA degree in Asian cultures and languages, I wrote a report about the history of Hindi, which was supervised by the director of HUF.</p>
      <p>As an MA student, I applied for a National Science Foundation (NSF) grant, which I won. For 3 years, the NSF would pay for my education and my living expenses. So, with my MA degree nearing its end, I applied to the MA/PhD program in The Department of Anthropology, from which I had earlier obtained my BA degree. I was admitted to the department, and I began to study anthropology even more seriously in the fall of 2014. During the next 3 years, when not back in Jaipur studying Hindi, I took 16 courses in anthropology at the graduate level. I stopped formally studying history and Hindi, though I kept up with both informally, having developed a studious disposition.</p>
      <p>With aspirations of entering the PhD phase of the degree, in 2017, I took my qualification exams with a committee of professors from The Department of Anthropology. At the time, my GPA was a respectable 3.6, but for various reasons, there was a misunderstanding between my committee and me. I failed my qualification exams and was asked to leave the department. Looking back on the failure, now I think that my anthropological reasoning was too unorthodox for the committee.</p>
      <p>Upset about not advancing to the PhD phase of the degree, I spent a few weeks considering my next move. For over a decade, I had worked toward becoming an anthropologist. Now I had to decide what else I might do with my life. Interested in programming, as a consequence of both my younger brother, who is a software engineer, and also the advertisements for the boot camps, I decided to enroll in a coding boot camp. But first I was going to spend some time teaching myself how to code.</p>
      <p>For the next few years, 2018 – 2020, I taught myself Python and JavaScript, learning from books and websites. I studied web development and also data structures and algorithms: The former is a job title one can have as a programmer, and the latter is a collection of knowledge that is used to evaluate the skills of a web developer during technical interviews in which candidates are asked to solve coding questions. I made a few web applications, and I created a public code repository for my work on data structures and algorithms.</p>
      <p>It was around this time, 2020 – 2021, that I landed my first job, as a Research Engineering Scientist Associate at Applied Research Laboratories (ARL), a laboratory associated with UT. I am proud of the title that I had, even though I was let go within six months after starting at ARL. After my departure from the lab, I decided my coding skills were strong enough to apply to The Coding Boot Camp at UT. I was admitted and spent a few months there studying coding in 2021.</p>
      <p>The boot camp lived up to its name. It was a rigorous experience. But my skills as a web developer improved, and I gained a certificate that I can use in my applications to work as a coder. Despite the certificate, however, I spent the next year, 2022, unsuccessfully applying to work as a web developer. I sent out dozens of well-crafted applications, but because of a lack of experience, I was not given even a single interview.</p>
      <p>Disillusioned by the job market in programming, I decided to retrain again. This time, in early 2023, I enrolled in the Google Project Management course, and I spent a couple of months learning about project management. An interesting and practical subject, I enjoyed the course, which also was rigorous: Dozens of quizzes evaluate the student’s progress through the material, and a student can only advance once a level’s quiz is passed. I quickly obtained the certificate, and it quickly paid off. I was offered an internship as an estimator for a construction start-up in San Diego.</p>
      <p>For a few months in 2023, I created estimates for constructions of accessory dwelling units (ADUs). After the internship, I then landed a job as a Project Coordinator for the architectural design start-up ADU Geeks. I worked at ADU Geeks for the rest of 2023. I left ADU Geeks at the end of 2023 to look for new opportunities, and so far in 2024, I have found work as a Hindi teacher online and also as a volunteer for The Casa de Luz Foundation.</p>
      <p>As a student, I achieved recognition in many subjects: anthropology, Asian studies, coding, and project management. I’m happy I’ve been able to find work in at least two of those subjects (Hindi and project management), and I continue to think seriously about all the subjects that I studied. For anthropology, I regularly think about topics like society and culture, economics and politics, race and gender, and colonialism and nationalism, just to name a few. I also write about the topics regularly on social media such as on my blog. For coding, I update this portfolio, and I continue to make web apps and to study and practice data structures and algorithms. I enjoy the reasoning involved in coding.</p>
      <p>Overall, in my education, I have read hundreds of books and hundreds of articles across the disciplines of the social sciences and humanities. I have listened to hundreds of lectures and written hundreds of essays about various topics. Throughout this practice, I have honed my abilities in research, reasoning, and writing. I like to write for my social media bio that my interests are science, programming, and Hindi.</p>
    </div>
  );
}

export default Education;
