import './Profile.css';


function Profile() { 
  return ( 
    <div> 
      <p className = 'profileText'>I relish a sophisticated science joke like, "Why don’t scientists trust atoms? Because they make up everything."</p>
      <p className = 'profileText'>On the scholastic front, I've not only embraced academic excellence but soared to remarkable heights, clinching positions nationally in the 99th and 96th percentiles on standardized tests, each time in two subjects. Growing up with a parent who was a geophysicist petroleum engineer with a geology degree, I was surrounded by the natural sciences from a young age. In formal education, I have a bachelor of arts degree in anthropology, master of arts degree in Asian cultures and languages with a focus on Modern Standard Hindi, and a coding boot camp certificate from The University of Texas at Austin, one of the top 50 universities globally. I also have a useful project management certificate from Google.</p>
      <p className = 'profileText'>From the university, my academic journey has provided me with a well-rounded understanding of anthropological theories and a focused attention to the concept of hierarchy. I was under the mentorship of an advisor who himself had been a student of Victor Turner, a key thinker in a branch of sociocultural anthropology, symbolic anthropology. I delved into the intricate dynamics of societal hierarchy, and in my interpretation of the phenomenon, I pursued objective rational thought in descriptions of hierarchy in different contexts. Through exploring this nuanced approach to hierarchy, I gained a deep understanding of the multifaceted nature of social relationships especially as hierarchy manifests in different countries at various levels of social organization such as local and national levels.</p>
      <p className = 'profileText'>Moreover, my practical experiences in language instruction included working closely with the director of the Hindi-Urdu Flagship, one center of a Department of Defense initiative to increase language proficiency in critical languages. Through rigorous language instruction, I honed my understanding of syntax, expanded my vocabulary, and cultivated the ability to provide verbally artful renditions of texts, fostering effective communication and nuanced expression. This experience strengthened my critical thinking abilities and heightened my cross-cultural competence. The skills I acquired from studying Hindi were reinforced during the four years I lived abroad in India.</p>
      <p className = 'profileText'>My familiarity with Hindi syntax proved advantageous -- for the consideration of syntax in the abstract -- when I enrolled in the university's coding boot camp. This experience solidified my understanding of JavaScript syntax and facilitated a comprehensive grasp of coding principles essential for developing web applications.</p>
      <p className = 'profileText'>The Google Project Management Certificate provided me with comprehensive insights into the project life cycle, emphasizing the essential documentation required to navigate tasks and milestones through project phases efficiently, leading to successful project completion.</p> 
      <p className = 'profileText'>For an occupation, I have held two distinguished positions: one as a Research Engineering Scientist Associate at Applied Research Laboratories and the other as a Project Coordinator for ADU Geeks.</p> 
      <p className = 'profileText'>In my capacity as a Research Engineering Scientist Associate, I collaborated within a team of proficient software engineers, contributing to the project's advancement through the meticulous execution of both automated and manual testing procedures. This multifaceted role demanded technical acumen, wherein I tested the precision and efficacy of our project through comprehensive methodologies.</p>
      <p className = 'profileText'>In my role as a Project Coordinator for ADU Geeks, I managed over 30 projects simultaneously, exhibiting adept organizational skills. My responsibilities encompassed keeping track of the status of each project and facilitating communication among the design team, vendors, and municipal authorities. This multifaceted engagement required adept navigation through the intricacies of collaborative project management. In essence, both roles demonstrated a synthesis of technical aptitude and organizational competence.</p>
      <p className = 'profileText'>Beyond academia and work, my intellectual pursuits span from coding data structures, algorithms, and neural networks to exploring the natural sciences' historical panorama -- an area of knowledge I informally explored in the past. Now, armed with a more profound understanding of the concepts through reading college textbooks and researching important topics, I find myself delving into the captivating realms of the natural sciences with a particular interest in molecular genetics.</p>
      <p className = 'profileText'>As a perspicacious science blogger and an unwavering vegan, I offer a synthesis of intellectual curiosity, scholarly achievement, and open-mindedness.</p>
    </div>
  );
}

export default Profile;
