import './Profile.css';


function Profile() { 
  return ( 
    <div> 
      <p className = 'profileText'>I relish a sophisticated science joke like, "Why don’t scientists trust atoms? Because they make up everything."</p>
      <p className = 'profileText'>On the scholastic front, I've not only embraced academic excellence but soared to remarkable heights, clinching positions nationally in the 99th and 96th percentiles on standardized tests, each time in two subjects. Growing up with a parent who was a geophysicist petroleum engineer with a geology degree, I was surrounded by the natural sciences from a young age. In formal education, I have a bachelor of arts degree in anthropology, master of arts degree in Asian cultures and languages with a focus on Modern Standard Hindi, and a coding boot camp certificate from The University of Texas at Austin, one of the top 50 universities globally. I also have a useful project management certificate from Google.</p>
      <p className = 'profileText'>My academic journey at the university has furnished me with a comprehensive understanding of anthropological theories, placing a particular emphasis on the intricacies of the concept of hierarchy. Guided by the mentorship of an advisor who himself was a student of Victor Turner—a pivotal figure in symbolic anthropology, a branch of sociocultural anthropology—I delved into the nuanced dynamics of hierarchy within the framework of social science. In my exploration of this subject, I employed objective and rational analyses to interpret hierarchy across diverse contexts. This approach enabled me to gain a profound insight into the multifaceted nature of social relationships, particularly as hierarchy manifests itself at various levels of social organization, ranging from local to national levels, across different countries.</p>
      <p className = 'profileText'>Furthermore, my hands-on involvement in language instruction extended to close collaboration with the director of the Hindi-Urdu Flagship, a focal point of the Department of Defense initiative aimed at enhancing language proficiency in strategically important languages. Engaging in rigorous language instruction, I refined my grasp of syntax, broadened my vocabulary, and developed the capacity to deliver verbally eloquent renditions of texts, facilitating effective communication and nuanced expression. This immersive experience not only fortified my critical thinking skills but also elevated my cross-cultural competence. The proficiency I gained in Hindi continued to be reinforced during my four-year residence in India.</p>
      <p className = 'profileText'>My familiarity with Hindi syntax proved advantageous-for the consideration of syntax in the abstract-when I enrolled in the university's coding boot camp. This experience solidified my understanding of JavaScript syntax and facilitated a comprehensive grasp of coding principles essential for developing web applications.</p>
      <p className = 'profileText'>The Google Project Management Certificate provided me with comprehensive insights into the project life cycle, emphasizing the essential documentation required to navigate tasks and milestones through project phases efficiently, leading to successful project completion.</p> 
      <p className = 'profileText'>For an occupation, I have held two distinguished positions: one as a Research Engineering Scientist Associate at Applied Research Laboratories and the other as a Project Coordinator for ADU Geeks.</p> 
      <p className = 'profileText'>In my capacity as a Research Engineering Scientist Associate, I collaborated within a team of proficient software engineers, contributing to the project's advancement through the meticulous execution of both automated and manual testing procedures. This multifaceted role demanded technical acumen, wherein I tested the precision and efficacy of our project through comprehensive methodologies.</p>
      <p className = 'profileText'>In my role as a Project Coordinator for ADU Geeks, I managed over 30 projects simultaneously, exhibiting adept organizational skills. My responsibilities encompassed keeping track of the status of each project and facilitating communication among the design team, vendors, and municipal authorities. This multifaceted engagement required adept navigation through the intricacies of collaborative project management. In essence, both roles demonstrated a synthesis of technical aptitude and organizational competence.</p>
      <p className = 'profileText'>Beyond academia and work, my intellectual pursuits span from coding data structures, algorithms, and neural networks to exploring the natural sciences' historical panorama, an area of knowledge I informally explored in the past. Now, armed with a more profound understanding of the concepts through reading college textbooks and researching important topics, I find myself delving into the captivating realms of the natural sciences with a particular interest in molecular genetics.</p>
      <p className = 'profileText'>As a perspicacious science blogger and an unwavering vegan, I offer a synthesis of intellectual curiosity, scholarly achievement, and open-mindedness.</p>
    </div>
  );
}

export default Profile;
